#!/bin/sh
#
# Adapted from https://github.com/MikeMcQuaid/dotfiles/blob/master/script/codespaces-post-start
#
# Run by github/github codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "vscode.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh vscode
fi

# Install some developer tools and setup Linux how I like it
apt-get install -y \
  zsh-autosuggestions

# Unset git settings that conflict with codespaces
git config --file /home/vscode/.config/git/config --unset user.email
git config --file /home/vscode/.config/git/config --unset user.signingkey
git config --file /home/vscode/.config/git/config --unset gpg.program
