tap "github/gh"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "kryptco/tap"
tap "nodenv/nodenv"
tap "ouchxp/nodenv"
tap "vitorgalvao/tiny-scripts"
# Shell extension to jump to frequently used directories
brew "autojump"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Decentralized dependency manager for Cocoa
brew "carthage"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Functional metaprogramming aware language built on Erlang VM
brew "elixir"
# Command-line tool to interact with exercism.io
brew "exercism"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Powerful, lightweight programming language
brew "lua"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# DNS benchmark utility
brew "namebench"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple NodeJS versions
brew "nodenv"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh", link: false
# Shell command parallelization utility
brew "parallel"
# Parallel gzip
brew "pigz"
# Parallel versions of OpenSSH and related tools
brew "pssh"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Ruby version manager
brew "rbenv"
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: true
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# This tool is a command-line client for the SSL Labs APIs
brew "ssllabs-scan"
# The cross-shell prompt for astronauts
brew "starship"
# Programatically correct mistyped console commands
brew "thefuck"
# Internet file retriever
brew "wget"
# Homebrew, but with Docker images
brew "whalebrew"
# JavaScript package manager
brew "yarn"
# Download YouTube videos from the command-line
brew "youtube-dl"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# GitHub CLI
brew "github/gh/gh"
# Deliver Go binaries as fast and easily as possible
brew "goreleaser/tap/goreleaser"
# Krypton command-line client, daemon, and SSH integration
brew "kryptco/tap/kr"
# Scrape build definitions from nodejs.org and iojs.org
brew "nodenv/nodenv/node-build-update-defs"
# Create aliases for nodenv Node versions
brew "nodenv/nodenv/nodenv-aliases"
# Migrate npm packages from one Node version to another
brew "nodenv/nodenv/nodenv-npm-migrate"
# Pick a node version from .nvmrc
brew "ouchxp/nodenv/nodenv-nvmrc"
# Quickly repair outdated/broken Casks from homebrew-cask
brew "vitorgalvao/tiny-scripts/cask-repair"
