tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "kryptco/tap"
tap "nodenv/nodenv"
tap "ouchxp/nodenv"

# Shell extension to jump to frequently used directories
brew "autojump"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext", link: true
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite", link: true
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Remove large files or passwords from Git history like git-filter-branch
brew "bfg"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Decentralized dependency manager for Cocoa
brew "carthage"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Distributed search & analytics engine
brew "elasticsearch"
# Functional metaprogramming aware language built on Erlang VM
brew "exercism"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# GNOME XML library
brew "libxml2"
# Powerful, lightweight programming language
brew "lua"
# LZMA-based compression program similar to gzip or bzip2
brew "lzip"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# High performance, distributed memory object caching system
brew "memcached"
# Open source relational database management system
brew "mysql@5.6", link: true
# DNS benchmark utility
brew "namebench"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple NodeJS versions
brew "nodenv"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Shell command parallelization utility
brew "parallel"
# Parallel versions of OpenSSH and related tools
brew "pssh"
# Cross-platform application and UI framework
brew "qt@5.5"
# Ruby version manager
brew "rbenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# This tool is a command-line client for the SSL Labs APIs
brew "ssllabs-scan"
# The cross-shell prompt for astronauts
brew "starship"
# Programatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# GitHub CLI
brew "github/gh/gh"
# Krypton command-line client, daemon, and SSH integration
brew "kryptco/tap/kr"
# Migrate npm packages from one Node version to another
brew "nodenv/nodenv/nodenv-npm-migrate"
# Pick a node version from .nvmrc
brew "ouchxp/nodenv/nodenv-nvmrc"
